name: 'Build'

on: [workflow_call, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          #         TODO: add version to a .nvmrc or at least a variable
          node-version: 18.12.1
          cache: npm
      - name: Install
        run: npm ci --omit=dev --prefer-offline
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # TODO (GAFI 19-03-2024): Add variable for this to avoid using ref when not provided
          name: lib-${{ github.head_ref }}
          path: ./dist
          if-no-files-found: error
