name: 'Build'

on:
  workflow_call:
    inputs:
      artifact-name:
        description: name of the artifact to be pushed
        required: true
        type: string
  workflow_dispatch:
    inputs:
      artifact-name:
        description: name of the artifact to be pushed
        required: false
        type: string

env:
  ARTIFACT_NAME: ${{ inputs.artifact-name || format('lib-{0}', github.sha) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install
        run: npm ci --omit=dev --prefer-offline
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./dist
          if-no-files-found: error
