name: "CD"

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  type-check:
    uses: ./.github/workflows/type-check.yml
  build:
    needs: [tests, type-check]
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: "lib-latest"
  build-storybook:
    needs: [tests, type-check]
    uses: ./.github/workflows/build-storybook.yml
    with:
      artifact-name: "storybook-latest"
  deploy-page:
    needs: build-storybook
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "storybook-latest"
  publish-package:
    needs: build
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          #         TODO: add version to a .nvmrc or at least a variable
          node-version: 18.12.1
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: npm ci --omit=dev --prefer-offline
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: "lib-latest"
          path: "./dist"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
