name: "CD"

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  type-check:
    uses: ./.github/workflows/type-check.yml
  build:
    needs: [tests, type-check]
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: "lib-latest"
  build-storybook:
    needs: [tests, type-check]
    uses: ./.github/workflows/build-storybook.yml
    with:
      artifact-name: "storybook-latest"
