name: "CD"

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  type-check:
    uses: ./.github/workflows/type-check.yml
  build:
    needs: [tests, type-check]
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: "lib-latest"
  build-storybook:
    needs: [tests, type-check]
    uses: ./.github/workflows/build-storybook.yml
    with:
      artifact-name: "storybook-latest"
  deploy-page:
    needs: build-storybook
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "storybook-latest"
  publish-package:
    needs: build
    uses: ./.github/workflows/publish-package.yml
    with:
      package-name: "lib-latest"
