name: "CI"

on: [push]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  type-check:
    uses: ./.github/workflows/type-check.yml
  build:
    needs: [tests, type-check]
    uses: ./.github/workflows/build.yml
  build-storybook:
    needs: [tests, type-check]
    uses: ./.github/workflows/build-storybook.yml
