name: 'Publish package'

on:
  workflow_call:
    inputs:
      artifact-name:
        description: name of the artifact to publish
        required: true
        type: string
  workflow_dispatch:
    inputs:
      artifact-name:
        description: name of the artifact to publish
        required: false
        type: string
        default: "lib-latest"

jobs:
  publish-package:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: npm ci --omit=dev --prefer-offline
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: "./dist"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
