name: 'Run tests'

on: [push, workflow_dispatch, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
#         TODO: add version to a .nvmrc or at least a variable
          node-version: 18.12.1
          cache: npm
      - name: Install
        run: npm ci
      - name: Run tests
        run: npm run test:unit
